# Generated by Django 3.1.1 on 2020-12-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
