# Generated by Django 3.1.1 on 2020-12-19 15:36

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201219_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='latitude',
            field=base.models.MinMaxFloat(),
        ),
        migrations.AlterField(
            model_name='target',
            name='longitude',
            field=base.models.MinMaxFloat(),
        ),
    ]
